# Generated by Django 5.0.1 on 2024-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joining',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
