# Generated by Django 5.0.1 on 2024-03-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderinfo_is_auth_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=15),
            preserve_default=False,
        ),
    ]
