# Generated by Django 5.0.1 on 2024-02-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('country', models.CharField(max_length=255)),
                ('street_address_1', models.TextField()),
                ('street_address_2', models.TextField(null=True)),
                ('city', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155, null=True)),
                ('zip_code', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupons', models.CharField(max_length=155)),
                ('date_expiration', models.DateField(verbose_name='%Y/%m/%d')),
                ('percent_discount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_to_deliver', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=255)),
                ('cart_data', models.JSONField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default=None, max_length=255)),
                ('is_auth_user', models.BooleanField(default=False)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.coupon')),
            ],
        ),
    ]
