# Generated by Django 5.0.1 on 2024-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_url',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
